In [1]:
# gauss_seidel
import numpy as np
Xs = [
      [
       # Soal 1
        [10,4,5], 
        [1,6,1], 
        [3,1,6]
      ],
      # Soal 2
      [
        [9,2,3,2],
        [4,11,2,3],
        [1,-4,8,-1],
        [5,-3,-6,16]
      ]
]

Ys = [
      # Soal 1
      [8,5,10],
      # Soal 2
      [12,9,6,21]
]

def gauss_seidel(x, y, epsilon = 0.01, t = 15):
  # 1. Ubah List menjadi Array
  x = np.array(x)
  y = np.array(y)

  # 2. Cari nilai diagonal
  diags = np.diag(np.abs(X))
  print(diags)

  # 3. Isi diagonal dengan 0
  np.fill_diagonal(x, 0)
  # print(x)

  # 4. Cari jumlah dari setiap baris/row
  # Parameter kedua pada fungsi p=np.sum
  # Dia nerima suatu axis
  # Default -> none (jumlahin semua baik baris maupun kolom)
  # axis = 0 -> jumlahin per kolom
  # axis = 1 -> jumlahin per baris
  off_diags = np.sum(np.abs(x), axis = 1)
  # print(off_diags)

  # 5. Cek diagonally dominant
  # Kalau misal tidak diagonal, langsung return
  # if np.all(diags > off_diags):
  #   print("Diagonally Dominant")
  if not np.all(diags > off_diags):
    print("Not Diagonally Dominant")
    return
  # 6. Ubah array x menjadi negatif semua
  x = -x

  # 7. inisialisasi value
  # x[0] -> ambil x index ke 
  # 0 karena selalu ada di persamaan
  mat_old = np.zeros(x[0].shape)
  # print(mat_old)

  # 8. iterasi
  for j in range(t):
    # 9. Bikin copy dari mat_old
    mat_new = np.array(mat_old)
    # 10. Iterasi untuk setiap var dalam persamaan
    # enumerate -> buat tampilin index ke berapa yang ditampung pada var k
    for k, row in enumerate(x):
      # 11. Hitung setiap variabel pada mat_new
      # row     [0,-4,-5]
      # mat_new [0,0,0]
      # (0*0) + (-4*0) + (-5*0)
      # loop berikutnya
      # row     [-1,0,-1]
      # mat_new [0.8,0,0]
      # (-1*0.8) + (0*0) + (-1*0) = 0.8
      mat_new[k] = (y[k] + np.dot(row, mat_new))/diags[k]
    print(f"{mat_new}")
    # 12. Cek Euclidean Distance
    # sqrt -> akar
    # dot -> mengalikan dan jumlahin
    # (mat_new - mat_old)^2 -> rumus dikuadratin
    dx = np.sqrt(np.dot(mat_new - mat_old, mat_new - mat_old))
    print(f"dx  = {dx}")
    # 13. Cek apakah euclidean distance < epsilon
    if dx < epsilon:
      print(f"Converged")
      return
    # 15. Update mat_old value
    mat_old = mat_new
  print(f"Not converged")


for (X, Y) in zip(Xs, Ys):
  print(f"X = {X}")
  print(f"Y = {Y}")
  gauss_seidel(X,Y)
  print("====================")

X = [[10, 4, 5], [1, 6, 1], [3, 1, 6]]
Y = [8, 5, 10]
[10  6  6]
[0.8  0.7  1.15]
dx  = 1.5660459763365826
[-0.055       0.65083333  1.58569444]
dx  = 0.9608704439365717
[-0.25318056  0.61124769  1.69138233]
dx  = 0.22806245930668492
[-0.29019024  0.59980132  1.7117949 ]
dx  = 0.04378822902864041
[-0.29581798  0.59733718  1.71501946]
dx  = 0.006938385517329205
Converged
X = [[9, 2, 3, 2], [4, 11, 2, 3], [1, -4, 8, -1], [5, -3, -6, 16]]
Y = [12, 9, 6, 21]
[ 9 11  8 16]
[1.33333333 0.33333333 0.75       1.23958333]
dx  = 1.9969866622405537
[0.7337963  0.07691498 0.85168087 1.41699054]
dx  = 0.6833793579381473
[0.7174607  0.01598398 0.84543322 1.40832798]
dx  = 0.06398055501766939
[0.73500849 0.01310142 0.84071565 1.40053473]
dx  = 0.019980595802418243
[0.73895342 0.01465008 0.8400227  1.39933246]
dx  = 0.004459418405188013
Converged
